import type { Incident } from '@/entities/incident/model/types';

const now = new Date();
const hoursAgo = (hours: number) =>
  new Date(now.getTime() - hours * 3_600_000).toISOString();
const minutesAgo = (minutes: number) =>
  new Date(now.getTime() - minutes * 60_000).toISOString();

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    title: 'Payment API latency spike',
    description:
      'Payment Service response time exceeded 2s threshold. Multiple checkout timeouts reported.',
    serviceId: 'service-a-payment',
    serviceName: 'Payment Service',
    severity: 'SEV2',
    status: 'INVESTIGATING',
    assigneeId: 'user-3',
    assigneeName: 'Park Responder',
    createdById: 'user-2',
    createdByName: 'Lee Manager',
    acknowledgedAt: minutesAgo(45),
    createdAt: hoursAgo(2),
    updatedAt: minutesAgo(10),
  },
  {
    id: 'inc-002',
    title: 'Notification delivery failures',
    description:
      'Notification Service failing to deliver SMS alerts. Error rate at 15%.',
    serviceId: 'service-b-notification',
    serviceName: 'Notification Service',
    severity: 'SEV1',
    status: 'ACKNOWLEDGED',
    assigneeId: 'user-3',
    assigneeName: 'Park Responder',
    createdById: 'user-1',
    createdByName: 'Kim Admin',
    acknowledgedAt: minutesAgo(20),
    createdAt: hoursAgo(1),
    updatedAt: minutesAgo(5),
  },
  {
    id: 'inc-003',
    title: 'Notification queue backlog',
    description:
      'Message queue depth growing. Push notifications delayed by 5+ minutes.',
    serviceId: 'service-b-notification',
    serviceName: 'Notification Service',
    severity: 'SEV3',
    status: 'TRIGGERED',
    createdById: 'user-2',
    createdByName: 'Lee Manager',
    createdAt: minutesAgo(30),
    updatedAt: minutesAgo(30),
  },
  {
    id: 'inc-004',
    title: 'Payment gateway timeout',
    description:
      'External payment gateway connection timeouts during peak hours.',
    serviceId: 'service-a-payment',
    serviceName: 'Payment Service',
    severity: 'SEV2',
    status: 'RESOLVED',
    assigneeId: 'user-3',
    assigneeName: 'Park Responder',
    createdById: 'user-2',
    createdByName: 'Lee Manager',
    acknowledgedAt: hoursAgo(48),
    resolvedAt: hoursAgo(47),
    createdAt: hoursAgo(50),
    updatedAt: hoursAgo(47),
  },
  {
    id: 'inc-005',
    title: 'Scheduled maintenance completed',
    description: 'User Service database migration completed successfully.',
    serviceId: 'service-c-user',
    serviceName: 'User Service',
    severity: 'SEV4',
    status: 'CLOSED',
    assigneeId: 'user-2',
    assigneeName: 'Lee Manager',
    createdById: 'user-1',
    createdByName: 'Kim Admin',
    acknowledgedAt: hoursAgo(72),
    resolvedAt: hoursAgo(71),
    createdAt: hoursAgo(73),
    updatedAt: hoursAgo(70),
  },
  {
    id: 'inc-006',
    title: 'Payment refund processing delay',
    description: 'Refund requests stuck in pending state for over 24 hours.',
    serviceId: 'service-a-payment',
    serviceName: 'Payment Service',
    severity: 'SEV3',
    status: 'POSTMORTEM_REQUIRED',
    assigneeId: 'user-2',
    assigneeName: 'Lee Manager',
    createdById: 'user-3',
    createdByName: 'Park Responder',
    acknowledgedAt: hoursAgo(120),
    resolvedAt: hoursAgo(118),
    createdAt: hoursAgo(122),
    updatedAt: hoursAgo(96),
  },
];
